sudo: required
dist: trusty
language: python
cache:
  - pip
  - apt

python:
  - 2.7
  - 3.6

install:
  - pip install -r dev_requirements.txt

script:
  - python setup.py test

notifications:
  email:
    on_success: never
    on_failure: never
